version: 0.0.{build}
os: Visual Studio 2017
build:
  project: RZE.sln
  parallel: true
  verbosity: normal
branches:
  only:
    - master
    - Sandbox
    - RenderRefactor
before_build:
  - cd RZE
  - GenerateSolutions.bat
  - cd RZE/_Project