version: 0.0.{build}
os: Visual Studio 2017

build:
  project: RZE/_Project/RZE.sln
  parallel: true
  verbosity: minimal
 
shallow_clone: true
 
branches:
  only:
    - master
    - Sandbox
    - RenderRefactor
    
configuration:
 - Debug
 - Release
 
install:
  - cd RZE
  - mkdir _Artifacts
  - GenerateSolutions.bat
  - cd _Project
  
before_build:
  - cd ..
  - GenerateSolutions.bat
  - cd _Project
  
after_build:
  - xcopy /y /d /s %APPVEYOR_BUILD_FOLDER%\RZE\Engine\Assets %APPVEYOR_BUILD_FOLDER%\RZE\_Artifacts
  - xcopy /y /d /s %APPVEYOR_BUILD_FOLDER%\RZE\_Build %APPVEYOR_BUILD_FOLDER%\RZE\_Artifacts
  - 7z a RZE_Engine_Artifacts.zip %APPVEYOR_BUILD_FOLDER%\RZE\_Artifacts
  
artifacts:
  - path: RZE/RZE_Engine_Artifacts.zip
    name: RZE_Engine_Artifacts