name: Windows
# Workflow file for windows
on:
  push:
    branches: [master, Sandbox]
  pull_request:
    branches: [master, Sandbox]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
    strategy:
      matrix:
        os: [windows-2019]
        buildconfig: [debug, release]
        include:
          - os: windows-2019
            shell: cmd
            compiler: cl
            target: Windows

    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "5.0.100"
        
    - name: Checkout
      uses: actions/checkout@v1
          
    - name: Generate a new project
      shell: cmd
      run: cd RZE/ && call GenerateSolutions.bat
      
    - name: Compile Project
      shell: cmd
      run: msbuild -m RZE/RZE.sln /property:Configuration="${{matrix.buildconfig}}"
      
    - name: Burn Assets
      shell: cmd
      run: call .\RZE\_build\${{matrix.buildconfig}}\SourceAssetBurner.exe
      continue-on-error: false
      
    - name: Asset Copy
      shell: cmd
      run: call .\RZE\AssetCpy.bat
      continue-on-error: false

    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: RZE v${{github.run_number}} - ${{matrix.buildconfig}}
        path: |
          RZE/_build/${{matrix.buildconfig}}
          !_RZE/build/${{matrix.buildconfig}}/*.lib
          !_RZE/build/${{matrix.buildconfig}}/*.pdb
          !_RZE/build/${{matrix.buildconfig}}/*.exp
          !_RZE/build/${{matrix.buildconfig}}/*.log
